---
title: "Rendering PDF from leopard"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Rendering PDF from leopard}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(minipdf)
```


```{r}

gc_to_gp <- function(gc) {
  with(
    gc,
    pgpar(
      col = col,
      fill = fill,
      lwd = lwd,
      lty = lty
    )
  )
}


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Translate leopard output to a PDF
#'
#' @param dfs \code{leopard} device output
#' @return SVG representation as a single string
#' @import grid
#' @import glue
#' @export
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
leopard_to_pdf <- function(dfs) {
  
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Ignore patterns, clip paths, masks, patterns etc
  # Just rendering the geometric primitives: circle, rect etc
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  keep <- 
    dfs$call$call %in% c(
      'circle', 'polygon', 'polyline', 'rect', 'text'
    )
  dfs$call <- dfs$call[keep, , drop = FALSE]

  doc <- create_pdf(800, 800)
  
  for (i in seq_len(nrow(dfs$call))) {
    
    call <- dfs$call[i, ]
    
    gc <- dfs$gc[call$gc_idx, ]
    # gp <- pgpar(alpha = 0.2)
    gp <- gc_to_gp(gc)
    
    
    switch(
      call$call,
      rect = {
        df <- dfs$rect[call$idx,]
        doc <- with(df, pdf_rect(doc, x0, y0, (x1 - x0), (y1 - y0), 
                                 gp = gp))
      },
      text = {
        df <- dfs$text[call$idx,]
        doc <- with(
          df,
          pdf_text(doc, str, x, y, fontsize = gc$fontsize)
        )
      },
      polyline = {
        df <- dfs$polyline[call$idx,]
        doc <- with(
          df,
          pdf_polyline(doc, x[[1]], y[[1]], gp = gp)
        )
      },
      circle = {
        df <- dfs$circle[call$idx, ]
        doc <- with(
          df,
          pdf_circle(doc, x, y, r, gp = gp)
        )
      },
      warning("not handled: ", call$call)  
    )
    
  }
  
  write_pdf(doc)
}




  library(leopard)
  library(glue)
  library(ggplot2)
  library(grid)
  
  
  f <- leopard(verbosity = 0, width = 6, height = 6, dev_opts = dev_opts(canHAdj = 0))
  # plot(1:10)
  ggplot(mtcars) +
    geom_point(aes(mpg, wt, colour = as.factor(cyl))) +
    # geom_line(aes(mpg, wt)) +
    # geom_polygon(aes(mpg, wt), fill = "hotpink", alpha = 0.2) +
    # facet_wrap(~cyl) +
    # theme_bw() +
    labs(title = "ggplot2 rendered to SVG with leopard")
  
  invisible(dev.off())
  dfs <- f()
  summary(dfs)
  dfs <- leopard::invert(dfs)
  # saveRDS(dfs, "data-raw/leopard1.rda")
  
  doc <- leopard_to_pdf(dfs)
  # cat(doc)
  
  writeLines(doc, "working/test-leopard.pdf")
  

```


